version: "3.9"

services:
  builder:
    container_name: builder
    build:
      context: ./
      dockerfile: builder/Dockerfile
    volumes:
      - ./builder:/source
      - ./shared:/shared

  reranker:
    container_name: reranker
    build:
      context: ./
      dockerfile: reranker/Dockerfile
    volumes:
      - ./reranker:/source
      - ./shared:/shared
    depends_on:
      - builder
      - searcher
      - common

  rewriter:
    container_name: rewriter
    build:
      context: ./
      dockerfile: rewriter/Dockerfile
    volumes:
      - ./rewriter:/source
      - ./shared:/shared
    depends_on:
      - builder
      - common

  searcher:
    container_name: searcher
    build:
      context: ./
      dockerfile: searcher/Dockerfile
    volumes:
      - ./searcher:/source
      - ./shared:/shared
    depends_on:
      - builder
      - common

  web_ui:
    container_name: web_ui
    build:
      context: ./
      dockerfile: web_ui/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SEARCHER_URL=searcher:8000
      - REWRITER_URL=rewriter:8000
      - RERANKER_URL=reranker:8000
    volumes:
      - ./web_ui:/source
      - ./shared:/shared
    depends_on:
      - reranker

  offline:
    container_name: offline
    profiles: ["offline"]
    build:
      context: ./
      dockerfile: offline/Dockerfile
    volumes:
      - ./shared:/shared
    depends_on:
      - builder

  common:
    container_name: common
    build:
      context: ./
      dockerfile: common/Dockerfile
    image: common
    deploy:
      replicas: 0
