version: "3.9"

services:
  builder:
    container_name: builder
    build:
      context: builder
      dockerfile: Dockerfile
    volumes:
      - ./builder:/source
      - ./shared:/shared
  
  reranker:
    container_name: reranker
    build:
      context: reranker
      dockerfile: Dockerfile
    volumes:
    - ./reranker:/source
    - ./shared:/shared
    depends_on:
      - builder
      - searcher
  
  rewriter:
    container_name: rewriter
    build:
      context: rewriter
      dockerfile: Dockerfile
    volumes:
    - ./rewriter:/source
    - ./shared:/shared
    depends_on:
      - builder
  
  searcher:
    container_name: searcher
    build:
      context: searcher
      dockerfile: Dockerfile
    volumes:
    - ./searcher:/source
    - ./shared:/shared
    depends_on:
      - builder
  
  web_ui:
    container_name: web_ui
    build:
      context: web_ui
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SEARCHER_URL=searcher:8000
      - REWRITER_URL=rewriter:8000
      - RERANKER_URL=reranker:8000
    volumes:
    - ./web_ui:/source
    - ./shared:/shared
    depends_on:
      - reranker